[package]
name = "mongodb-poem-app"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
mongodb = "2.3.1"
poem = "1.3.49"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
shuttle-service = { version = "0.8.0", features = ["web-poem"] }
shuttle-shared-db = { version = "0.8.0", features = ["mongodb"] }
=======
mongodb = "2.3.0"
poem = "1.3.35"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shuttle-service = { version = "0.7.2", features = ["web-poem"] }
shuttle-shared-db = { version = "0.7.2", features = ["mongodb"] }
>>>>>>> origin/update#1
