[package]
name = "postgres"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
serde = { version = "1.0.148", features = ["derive"] }
shuttle-aws-rds = { version = "0.8.0", features = ["postgres"] }
shuttle-service = { version = "0.8.0", features = ["web-tide"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres"] }
=======
serde = { version = "1.0", features = ["derive"] }
shuttle-aws-rds = { version = "0.7.2", features = ["postgres"] }
shuttle-service = { version = "0.7.2", features = ["web-tide"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres"] }
>>>>>>> origin/update#1
tide = "0.16.0"
