[package]
name = "postgres"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
poem = "1.3.35"
serde = "1.0"
shuttle-service = { version = "0.7.2", features = ["web-poem"] }
shuttle-shared-db = { version = "0.7.2", features = ["postgres"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres"] }
